language: java
addons:
  apt:
    packages:
    - xmlstarlet
    - graphviz
jdk:
- oraclejdk11
after_success:
- wget -O settings.xml https://raw.githubusercontent.com/pousse-cafe/pousse-cafe-deploy/master/snapshot_release_settings.xml
- "./can_auto_deploy.sh && mvn deploy --settings settings.xml"
env:
  global:
  - secure: fu3eWZVdl6hALk715MbfiC+gKMjQSxATxevwGDOa9S+d5kKm0XTVyqaXZ6SD1YVxZzCwh5BEz5iHYEHrirvbWgOpEHxjzlgx6ya2enN+vvVVdFNa4/kyjBRhvuwW9Hgwndzubz01KCUWKY5UbvY+5GSFcXBrjwwiDoUHUoQUUG9laFCkdp42hI8o6lSXlZYJJNRHhY7cTVU8DIR3K6VFgenaIwTPdyBlAtAJexEJ8GLR0d9vBvUcXYWKKp3ZCM8L8kXXEsbOpWTD7+BgSp1AZ7nj+sePm3zjqKMIH4+BSmHWGhJXSZBSkpZi/rD6/rPObdwYFJmb9tdEYPn0pqrUEsecAxlRNt/1UmZLb+SHVyykFt0qJPf4wPh0dq1MLifEMkXfZ4s6kCQSYrRqSriH4lfsS/CIQkQqQABOmIS4de5KCquzEV4lclC8TbCifw/q45DNbCFUX18QrGjN56x7QpFudBVx4Q/zWN7S/5xcK8CRCqh59wwHXX0ts8P0LryonDfbXlMIrxAJPZe9h5RAk5DdmrSCy0kQz7TQu1dsiNjpakHDw3HbGTAivHwYQHsP9ZGH5MZkIHCuXffRkOHhU/98c9+LsT4+4nbQ2yxTTDWIrxEVcNW2ose/+6v7ypxE3Ns61wCuUJSgH2dzi3GD3ArhPATGXFn9jiSZeT6Q6Jg=
  - secure: gEzu4vW/VElC8J37LMmliGvEoIolv9hArCcUx4EDMXjh0AEMOroWej+iSsWFuCP9EIqsIGIWaV2Ml6IG+J8jelDLWEOalLLdM8iXFyIF6O6XIyP4bGfB97lnyhudj9YurUpNH18hZ1A40JuW34YTdHlvnUfASfzFCSckmi+E/7J0HWNcYKv3zsepBfpa1/8Twc+LRsqLcm5VkxcsSTGZcTLT17+zDqrdnP1tTpUi+3+ddy3HSTOKbOFksn+2oOG7H3m8CT6MmFvP0DRJepG0pYerq7Rp6c1gLaO/m4AnFGmMPS20tE24IWo1k/PpRFT1GOPtk+5oaV+09Cy8ndCIIdf2MhhRd4JH9XQaaOaHKEIh6uGHXl+KlW0O1FhjQJjMZl+ciqp/wz47cbthS348udFDHTbWJlq0VLoMGjVSFk6jsEC79R1R+8Tz7ptBp3fFAI2vsf0jtzl8zScFy/DPFf0z+8vq5gGRFtRPQKcuHiqePMvZqHHjSbKxNy85y3aN4iZHfC+r2iTHq94uIzJejxjNlXe3Bs0y4U309e2HVhTg5K4Fvv3dFmUsXAyXzr6Y4FIH6Q5JSDCYLCAuCBJlrg263zwpZvvCf+M7uyaR32WHLpw7LG6eGUDI1zJ+326vBSMgvPAGAyRmXpP2S2/XJCmnLG5BBsSHSKqJ0QQZXi4=
