language: java
addons:
  apt:
    packages:
    - xmlstarlet
    - graphviz
jdk:
- oraclejdk11
after_success:
- wget -O settings.xml https://raw.githubusercontent.com/pousse-cafe/pousse-cafe-deploy/master/snapshot_release_settings.xml
- "./can_auto_deploy.sh && mvn deploy --settings settings.xml"
env:
  global:
  - secure: fu3eWZVdl6hALk715MbfiC+gKMjQSxATxevwGDOa9S+d5kKm0XTVyqaXZ6SD1YVxZzCwh5BEz5iHYEHrirvbWgOpEHxjzlgx6ya2enN+vvVVdFNa4/kyjBRhvuwW9Hgwndzubz01KCUWKY5UbvY+5GSFcXBrjwwiDoUHUoQUUG9laFCkdp42hI8o6lSXlZYJJNRHhY7cTVU8DIR3K6VFgenaIwTPdyBlAtAJexEJ8GLR0d9vBvUcXYWKKp3ZCM8L8kXXEsbOpWTD7+BgSp1AZ7nj+sePm3zjqKMIH4+BSmHWGhJXSZBSkpZi/rD6/rPObdwYFJmb9tdEYPn0pqrUEsecAxlRNt/1UmZLb+SHVyykFt0qJPf4wPh0dq1MLifEMkXfZ4s6kCQSYrRqSriH4lfsS/CIQkQqQABOmIS4de5KCquzEV4lclC8TbCifw/q45DNbCFUX18QrGjN56x7QpFudBVx4Q/zWN7S/5xcK8CRCqh59wwHXX0ts8P0LryonDfbXlMIrxAJPZe9h5RAk5DdmrSCy0kQz7TQu1dsiNjpakHDw3HbGTAivHwYQHsP9ZGH5MZkIHCuXffRkOHhU/98c9+LsT4+4nbQ2yxTTDWIrxEVcNW2ose/+6v7ypxE3Ns61wCuUJSgH2dzi3GD3ArhPATGXFn9jiSZeT6Q6Jg=
  - secure: A1vTtRKRboMmrkUvJoAxsUAZhjQ7WmU7MFQQ+q3bR9fDmy4H/GRMa+EKiOYZonGZ92A125HBnBtKwjo304ggVBplgvtH0QiZ8wy2PZtl7E0EA8kHm7bsmenCcFSJJeyYTKtgpsk6YP6MTlueD9yPFynhQJGgRx6MsbqXJOj97/IxgKrolyPOo6ZVHWnpgFPiq4gSPAJKAl6Xvk5smkZgz/Ab/pgsPTeE4u9yDPFPJpbBWUW6/vNq3f8g0Mem/dEoFit0B/2zGbjjGEujk9+PB/aXhEVDmHFPwsM/t2VRy5Hikaf2KPMBYz6Hf/BOH5za8FiNoZPDKyD1A6aSCnj5ua1Rl4cekIpXsVzJCh4aMmlzjPaKR9/WVAzy9c4oeOiDBobICbwB/CoyiwMdwlNggVDYONcLKFOVbPCLAISD/SvqtT6ElqepNvA2Vw9GzfBWqUPrQsPcuZXqpp3K+SX2sj6T08SQ5b/RM2Me0kU88cc/3OcBpsFgeJWY/bQYRoUCcfFuTC3zuLJgaq3LcNJaTxcja8HETqQJkZmN0Fl7Ih73Lxyi7RlJIkfwbmwFLD583ejK29OXQ6gKxJeBmsC0lg3oKcsE86h0iDSJIydyqa1JMXCWr5gtBzMkHGNVORPUmsNlkUYanCLf+KDJBrQgBj8SezB+d/Fqq3mozV6ahTQ=
